### ISSUE TITLE
There is a problem with the search bar style/搜索栏样式问题

### ISSUE THREAD

**Issue by tabris233** [brookhong/Surfingkeys#1247]
## Error details

SurfingKeys: 0.9.64

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

URL: <The_URL_Where_You_Find_The_Issue>

## Context

搜索栏样式问题,  尝试改了下主题配置但好像还是不行.
There is a problem with the search bar style. I tried to change the theme configuration but it still didn't work.

```css
settings.theme = `
.sk_theme {
font-family: Input Sans Condensed, Charcoal, sans-serif;
font-size: 11pt;
background: #282828;
color: #ebdbb2;
}
.sk_theme tbody {
color: #b8bb26;
}
.sk_theme input {
color: #d9dce0;
}
.sk_theme .url {
color: #98971a;
}
.sk_theme .annotation {
color: #b16286;
}
.sk_theme .omnibar_highlight {
color: #ebdbb2;
}
.sk_theme #sk_omnibarSearchResult>ul>li:nth-child(even) {
background: #282828;
}
.sk_theme #sk_omnibarSearchResult>ul>li:nth-child(odd) {
background: #282828;
}
.sk_theme #sk_omnibarSearchResult>ul>li.focused {
background: #d3869b;
}
#sk_status, #sk_find {
font-size: 28pt;
}`;
``` 

![image](https://user-images.githubusercontent.com/29500388/83235277-36023e00-a1c4-11ea-9ada-469838370a7c.png)
