### ISSUE TITLE
How to hide hint tips when taping `f` ?

### ISSUE THREAD

**Issue by yangzexia** [brookhong/Surfingkeys#2257]
![Image](https://github.com/user-attachments/assets/c6cebb79-566e-48c8-9876-a34578d5690f)

**Comment by aspiers** [comment]
Not sure if I understand the question, but you can press `Escape` to hide the hints.

**Comment by 0900304132** [comment]
surfingkeys settings -> advanced mode -> settings.theme 
insert 
```css
#sk_status {
    display:none !important;
}
```
